### ISSUE TITLE
Session Closed Unexpectedly when Refreshing page

### ISSUE THREAD

**Issue by haashem** [jamiekurtz/Mvc4ServicesBook#7]
thanks for writhing this great book. I read it and a lot of technics for better writing codes.
But I've encountered an strange problem. I have implemented my custom membership using NHibernate which made it a lot easy working with membership data. I have created a repository for workig with model.
But here is the problem: when I first run the app. I can create a new member. but when I hit the refresh button, the session will be closed unexpectedly!! 
first run:
1- everything works well

after hitting refresh button:
1- a new session bind to the current context.
2 - the new session will be injected the repository (session is open)
3- the ActionTransactionHelper calls beginTransaction() 
4- customMembership createUser (....) called
5- but when the  _userRepositoy.save(user) called in the repository session is closed!!!!

note: still endTransaction and closeSession isn't called. but how session is closed?

I have upoaded my sample code. for testing just create and empty database and change connection string. then go to localHost:*****/api/categories and check (user and pass doesn't required)
![session closed](https://f.cloud.github.com/assets/3206748/2163598/45431606-94e1-11e3-8f5d-d105a84deb0e.jpg)

download sample project:
https://www.dropbox.com/s/o63wjng5f799fii/Hashem-MVC4ServicesBook.rar

I'll appreciate if you could help me in this scenario.

**Comment by jamiekurtz** [comment]
Hey there... I'll take a look at this issue over the weekend. Kind of
sounds like a lifetime management issue - i.e. not releasing the previous
ISession, or maybe you're getting extra ISession instances somehow?? I'll
get back to you tomorrow.

**Comment by haashem** [comment]
thanks for your help and devoting time. I checked a lot and tried different way I knew. it only happens when for the second time I want to do CRUD operations with my customMembership.  
for other entities it works like a charm!

**Comment by jamiekurtz** [comment]
ok, so I think the problem is that the ASP.NET Membership class is keeping
a static instance of your FNHMembershipProvider class - which in turn has a
reference an ISession instance. So in the CategoriesController.Get()
method, you use the static property Membership.Provider to get your own
custom provider... in the provider's constructor it uses the
container/resolver to create an instance of IRepository<User>. The
Repository instance has injected an ISession - which is being managed by
the ActionTransactionHelper. When the first call completes,
the ActionTransactionHelper closes the ISession instance. When you hit
Refresh, however, the first instance of your FNHMembershipProvider class is
still in memory, and so is its _userRepository instance - which still has
the _session field that was closed on the previous call.

I hope that makes sense.

To test this theory, I made a slight modification to the
FNHMembershipProvider. Once this change/hack was made, hitting the Refresh
button worked as expected:
1. Added a new method to get an IRepository<User> instance from the
   resolver on the fly (as opposed to in the constructor)
2. Used that method within the GetUserNameByEmail() method

Like this:

```
    private IRepository<User> GetRepository()
    {
        var userRepository =
```

DependencyResolver.Current.GetService<IRepository<User>>();
            if (userRepository == null)
                userRepository =
(IRepository<User>)GlobalConfiguration.Configuration.DependencyResolver.GetService(typeof(IRepository<User>));
            return userRepository;
        }

And:

```
    usr = GetRepository().Get(user => user.Email ==
```

email).SingleOrDefault();

So I think the bottom line is... the ASP.NET Membership class is NOT
creating an instance of your provider on every call. As such, you need to
treat your provider as a static-ish class, and thus make sure to avoid
using any instance fields to hold connections, ISessions, etc. At least not
without being careful of their respective lifetimes.

Let me know if that doesn't make sense.

Jamie

**Comment by haashem** [comment]
wow, you are my hero. I worked on it for days without hope. but you solved it so fast. thanks a lot. it works like a charm!!

so is there any other way to use my customMembership without using static property provider? or can I initialize the private method _userRepository on every request without Calling getRopositoy()? I want the CustomMembership be like a blackBox just call memberShip.getUser(username)?

**Comment by jamiekurtz** [comment]
I haven't tried this myself, but here are a couple good ideas:

http://stackoverflow.com/questions/4193484/how-do-i-control-membershipprovider-instance-creation-lifetime

http://stackoverflow.com/questions/2753424/dependency-injection-with-custom-membership-provider

You could also just create your own DelegatingHandler class and simply use
your custom provider to authenticate and set the thread principal. That way
you don't even need to use the ASP.NET membership model at all. That's
actually what I usually do.
